context.modules = [
  {
    name = libpipewire-module-filter-chain
    args = {
      node.description = "Broadcast Filter"
      media.name        = "Broadcast Filter"
      filter.graph = {
        nodes = [
          {
            type   = ladspa
            name   = deepfilter
            plugin = /usr/lib/ladspa/libdeep_filter_ladspa.so
            label  = deep_filter_stereo
            control = {
              "Attenuation Limit (dB)" = 100
            }
          }
        ]
      }
      capture.props = {
        node.name    = "broadcast_filter_sink"
        media.class  = Audio/Sink
        audio.rate   = 48000
      }
      playback.props = {
        node.name    = "broadcast_filter_output"
        node.passive = true
        audio.rate   = 48000
      }
    }
  }
]
